name: Build and Release APK

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: List build outputs
      run: |
        echo "=== Build outputs ==="
        find app/build/outputs -name "*.apk" -type f
        echo "=== APK directory contents ==="
        ls -la app/build/outputs/apk/release/ || echo "Release directory not found"
        echo "=== All outputs ==="
        find app/build/outputs -type f
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/release/*.apk
        tag_name: v1.0.0-${{ github.run_number }}
        name: Release v1.0.0-${{ github.run_number }}
        body: |
          ## Auto Build Release
          
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Time: ${{ github.event.head_commit.timestamp }}
          
          ### Download
          Click the file above to download APK
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 